### ISSUE TITLE
Upgrade to latest open release

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/ssrs-date-selector#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by AngelaIp** [comment]
Hi,

I currently use this project as basis for a quantity selector. With the following mods the project will be basically work for SP9 in Firefox:

1.	Form: DataRangeSelector
Color run_report button to make the button visible

2.	Method: Report_date_select
Line 22-23: Replace` &amp; `with `& `in url string (without this change the Report wasn´t generated in my environment)

3.	Method: run_report_button_click
Line 13+14: Replace `window` with `parent`

There are some further outdated codelines inside. E.g. the showModalDialog needs also to be replaced.

**Comment by EliJDonahue** [comment]
Retarget to current open release: 11.0 SP12.

**Comment by sampoearas** [comment]
#2 will allow the project to work in 11 SP12 with a couple more additions (ampersand change mentioned above was not in PR)
